package jp.gr.java_conf.ka_ka_xyz.jmx_watchdog.handler.impl;

/**
 * dtoに指定されたannotaion情報を元にMXBeanから情報を移行する際に発生する例外。
 * */
public class AnnotationHandlingException  extends RuntimeException{
	
	/**
	 * generated by Eclipse
	 */
	private static final long serialVersionUID = -783055594080223971L;

	public AnnotationHandlingException(){super();}
	
	public AnnotationHandlingException(String msg){super(msg);}
	
	public AnnotationHandlingException(Throwable t){super(t);}
	
	public AnnotationHandlingException(String msg, Throwable t){super(msg, t);}

}
